/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakingRewardsFactorySol from "./StakingRewardsFactory.sol";
export type { stakingRewardsFactorySol };
import type * as wttrustSol from "./WTTRUST .sol";
export type { wttrustSol };
export type { StakingRewards } from "./StakingRewards";
export type { TSWP } from "./TSWP";
export type { TestToken } from "./TestToken";
export type { UniswapV2Router02 } from "./UniswapV2Router02";
